packages:
  - packages/*

catalog:
  "@release-it/bumper": ^7.0.2
  "@types/node": "^22.13.10"
  dotenv-cli: ^8.0.0
  eslint: ^9.22.0
  prettier: ^3.5.3
  release-it: ^18.1.2
  shellcheck: ^3.1.0
  tsup: ^8.4.0
  typescript: ^5.8.2
